name: Build APK
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-8-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
        python -m pip install --upgrade pip
        pip install --user --upgrade Cython==0.29.19
        pip install --user --upgrade buildozer

    - name: Build with Buildozer
      run: |
        # Accept Android SDK licenses
        mkdir -p ~/.android
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > ~/.android/repositories.cfg
        yes | buildozer android accept_sdk_license
        
        # Build the APK
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: sokarara-app
        path: bin/*.apk
